---
title: "GHA Survival Analysis"
author: "Han Yin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    fig_caption: true
    fig_crop: no
    number_sections: no
    df_print: paged
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
editor_options:
  chunk_output_type: inline
---

```{r setup knit, include=FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.pos = "H",
	message = FALSE,
	warning = FALSE,
	external = TRUE,
	echo = TRUE
)
```

```{r load library and dataset}
library(magrittr)
library(tidyverse)

library(survival)
library(survminer)

setwd("/Users/hanyin/Dropbox (CSU Fullerton)/Research Project/Flies/Kshama -- statistical analysis/GHA")

rep12 = readxl::read_excel("data/winter_rep12_for_R_SSMI.xlsx")
rep3 = readxl::read_excel("data/winter_rep3_for_R_SSMI.xlsx") 
```


## Data Manipulation

```{r clean data}
# cut-off at Day 19 to remove missing
rep12 = rep12 %>% filter(Day <= 19) 
rep3 = rep3 %>% filter(Day <= 19) %>% 
  mutate(Death = as.numeric(Death), `Initial density` = as.numeric(`Initial density`))

# clean treatment labels
reps = bind_rows(rep12, rep3) %>% 
  mutate( Treatment = sapply(Treatment, function(x) strsplit( gsub(" ","",x), "-")[[1]][1]) )

# leave Control and GHA of 5 mins
reps = reps %>% filter(Treatment!="ARSEF" & CO2=="15 sec")
```

```{r get status and dummy}
# count dead
df_dead = reps[ rep(c(1:nrow(reps)), reps$Death), ] %>% mutate(Death = 1) %>% 
  select(Replicate,Population,Cage_Number,CO2, Treatment,Sex,Day,Death)

# count alive
df_alive = reps %>% 
  group_by(Replicate,Population,Cage_Number,CO2,Treatment,Sex) %>% 
  summarise(Death=sum(Death), `Initial density`=max(`Initial density`)) %>% 
  mutate(Alive=`Initial density`-Death, Day=19)

df_alive = df_alive[ rep(c(1:nrow(df_alive)), df_alive$Alive), ] %>% 
  mutate(Death = 0) %>% 
  select(Replicate,Population,Cage_Number,CO2, Treatment,Sex,Day,Death)

# merge dead and alive
df = bind_rows(df_alive, df_dead)

# convert to dummies
df = df %>% mutate(Fungal=(Treatment=="GHA")+0, Male=(Sex=="M")+0)
```


## Raw Data Plot

```{r calculate and plot survival percent}
reps %>% 
  group_by(Treatment,Sex,Day) %>% summarise(Death=sum(Death), `Initial density`=sum(`Initial density`)) %>% 
  group_by(Treatment,Sex) %>% mutate(Death=cumsum(Death), `Survival Percent`=1-Death/`Initial density`) %>%
  ggplot(aes(x=Day, y=`Survival Percent`*100, color=Sex, linetype=Treatment)) +
  geom_line() +
  geom_point() +
  # scale_color_manual() +
  scale_linetype_manual(values = c("Control"="dashed","GHA"="solid")) +
  labs(x="Days", y="Survival Percent (%)") +
  theme_classic()
```

## Cox Modeling

### time intervals

```{r find time intervals}
mod = coxph(Surv(Day, Death) ~ Fungal + Male + Fungal*Male, data = df)
# cox.zph(mod)

a1 = 8; a2 = 12
df2 = survSplit(df, cut=c(a1,a2), end="Day", event="Death", start="Start") %>%
  mutate(gt1 = (Start==0)+0, gt2 = (Start==a1)+0, gt3 = (Start==a2)+0)

mod = coxph(Surv(Start,Day,Death) ~ Fungal +
              Male:gt1 + Male:gt2 + Male:gt3 + 
              Fungal:Male:gt1 + Fungal:Male:gt2 + Fungal:Male:gt3, data = df2)
# cox.zph(mod)
# cox.zph(mod, transform=log)
# extractAIC(mod)
```

### hazard table
```{r}
beta = coef(mod)
diff = c(0,  # fungal
         -1,0,0, # male
         -1,0,0) # fungal*male

t_obs = (beta%*%diff) / sqrt(t(diff) %*% vcov(mod) %*% diff)
# c(exp(beta%*%diff), 2*(1-pt(abs(t_obs), length(beta))))
```



### calculate survival probabilities

```{r calculate survival probabilities}
get_time_data = function(data){
  data = survSplit(data, cut=a1, end="Day", event="Death", start="Start") %>% 
    mutate(gt1 = (Start==0)+0, gt2 = (Start==a1)+0, gt2 = (Start==a2)+0,
           t1_male = Male*gt1, t2_male = Male*gt2,
           fun_male = Fungal*Male, t1_int = Fungal*Male*gt1, t2_int = Fungal*Male*gt2)
  return(data)
}

category = ungroup(df) %>% select(Fungal,Male) %>% unique() %>% set_rownames(NULL)
time_intervals = data.frame(Start=c(0,a1,a2), Day=c(a1,a2,19), gt1=c(1,0,0), gt2=c(0,1,0), Death=0)

pred_surv = function(data){
  mod = coxph(Surv(Start, Day, Death) ~ Fungal + Male + t1_male + t2_male + 
                fun_male + t1_int + t2_int,
              data = get_time_data(data))
  surv = c()
  for (i in 1:nrow(category)){
    i = 2
    test = category[rep(i,nrow(time_intervals)),] %>% 
      bind_cols(time_intervals, row.names = NULL) %>% get_interaction()
    time = summary(survfit(mod, newdata = test, individual = TRUE))$time
    insert = setdiff(1:18, time)
    time = c(time, insert)
    est = c(1, summary(survfit(mod, newdata = test, individual = TRUE))$surv,
            rep(NA, length(insert)))
    surv_i = data.frame(category[i,], est, day = c(0,time)) %>% arrange(day)
    surv = rbind(surv, surv_i)
  }
  return(surv)
}

est = pred_surv(df) 
```


### Bootstrap confidence intervals

```{r bootstrap ci}
B = 1000
bound = 0.95

# function to extract bounds
ci_calculator = function(data){
  ci = data.frame(lower = as.numeric(), upper = as.numeric())
  for (i in 1:max(data$Day)) {
    ci[i,1] = quantile(data$est[data$Day == i], (1-bound)/2, na.rm = TRUE)
    ci[i,2] = quantile(data$est[data$Day == i], (1+bound)/2, na.rm = TRUE)
  }
  return(ci)
}

# repeat B times
dummy = c()
for (i in 1:B){
  dummy_i = c()
  for (j in 1:nrow(category)){
    dummy_ij = merge(df, category[j,])
    a = nrow(dummy_ij)
    rows_to_take = sample(a, a, replace = TRUE)
    dummy_i = rbind(dummy_i, dummy_ij[rows_to_take,])
    }
  dummy_i = pred_surv(dummy_i)
  dummy = bind_rows(dummy, dummy_i)
}

# get confidence intervals
survs = c()
for (i in 1:nrow(category)){
  ci = merge(dummy, category[i,]) %>% mutate(Day=day) %>% ci_calculator()
  surv = merge(est, category[i,]) %>% arrange(day)
  surv = cbind(surv, ci)
  survs = rbind(survs, surv)
}

# recode labels
df_plot = survs %>% 
  mutate(Treatment = ifelse(Fungal==1, "GHA","Control"), Sex = ifelse(Male==1, "Male","Female"))
```


### plot survival probability
```{r plot prediction and bounds}
set_line_size = 1.8      
set_point_size = 2.1  

set_err_size = 1.5     
set_err_width = 0.5    
set_alpha = 0.7


thm = theme(axis.line = element_line(color="gray54", size=0.1, linetype="solid"),
            panel.background = element_rect(fill = NA),
            legend.key = element_rect(fill = NA),
            legend.background = element_rect(fill = NA),
            plot.title = element_text(size = 15, hjust = 0.5)) 

ggplot(df_plot, aes(x=day, y=est, color=Sex, linetype=Treatment, ymin=lower, ymax=upper)) +
  geom_line(size = set_line_size) + geom_point(size = set_point_size) + 
  geom_errorbar(size = set_err_size, width = set_err_width, alpha = set_alpha) +
  
  scale_linetype_manual(values = c("Control"="dotted","GHA"="solid")) +
  scale_color_manual(values = c("Female"="#32CD32", "Male"="#FA8072")) +
  
  labs(x="Days", y="Survival Probability") +
  thm +
  ylim(0,1) +
  guides(linetype = guide_legend(order = 1), color = guide_legend(order = 2))
```


